### ISSUE TITLE
XP Book not pulling all experience.

### ISSUE THREAD

**Issue by Phr3d13** [charlyb01/xp_storage#9]
I have a level 3 book, I have a hair over 31 levels...
![image](https://user-images.githubusercontent.com/8862382/105622424-b9217580-5ddf-11eb-94fb-35d4112b9f11.png)
I use the book...
![image](https://user-images.githubusercontent.com/8862382/105622447-e3733300-5ddf-11eb-8308-08c520b5e6b4.png)
and it doesn't take all the experience.

**Comment by Phr3d13** [comment]
but doing a "/experience query {name} points" says I have 0 points...

**Comment by Phr3d13** [comment]
Same thing happens with another player on my server, exact same amount of exp bar filled as me, but still 0 points when the above command is sent

**Comment by Phr3d13** [comment]
More info... If I put all the experience in the book, then set my experience to zero twice, then "flip/flop" with the book, the bar keeps the correct levels.

**Comment by charlyb01** [comment]
Yes I had noticed this during testing, but it actually takes all the experience as you noticed. It's like a graphic bug.
As you also encountered this, I'll try again to figure it out. Thanks for report ;)

**Comment by charlyb01** [comment]
That's fixed! Was actually quite easy to solve as it was ust a graphic bug because of floating values. I will update the mod a bit later
